name: Run Tests and Publish Report
on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  test-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install robotframework robotframework-requests

      - name: Run Robot Tests
        run: |
          mkdir outputs
          robot --outputdir outputs tests/ || true

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v4

      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './outputs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
